name: Clean up webhooks
on:
  workflow_dispatch

jobs:
  fetchWebhooks:
    runs-on: ubuntu-latest
    outputs:
      hook_ids: ${{ steps.get_webhooks.outputs.hook_ids }}

    steps:
      - uses: octokit/request-action@v2.x
        id: get_webhooks
        with:
          route: GET /repos/hashicorp/terraform-random-1/hooks
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: "jq -n '${{ steps.get_webhooks.outputs.data }}' | jq -rc '[.[] .id]' > ids.json"
      - run: |
          echo "hook_ids=$(cat ids.json)\n" >> $GITHUB_OUTPUT
  debugOutputs:
    runs-on: ubuntu-latest
    needs: [ fetchWebhooks ]
    steps:
      - run: echo '${{needs.fetchWebhooks.outputs.hook_ids}}'
  cleanWebhooks:
    runs-on: ubuntu-latest
    needs: [ fetchWebhooks ]
    strategy:
      matrix:
        value: ${{fromJSON(needs.fetchWebhooks.outputs.hook_ids)}}
    steps:
      - uses: octokit/request-action@v2.x
        id: delete_webhook
        with:
          route: DELETE /repos/hashicorp/terraform-random-1/hooks/${{ matrix.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
