name: Clean up webhooks
on:
  workflow_dispatch

jobs:
  cleanWebhooks:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_webhooks
        with:
          route: GET /repos/hashicorp/terraform-random-1/hooks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo hooks found: '${{ steps.get_webhooks.outputs.data }}'"
      - run: "echo failed to fetch hooks. Request failed with status '${{ steps.get_webhooks.outputs.status }}'"
        if: ${{ failure() }}
